# ngl\_resum: a package to resum non-global logarithms at leading logarithmic accuracy

If you use the package ngl\_resum, please cite [doi:10.1007/JHEP09(2020)029](https://inspirehep.net/literature/1798660).

In this documentation we show some features of ngl\_resum. In particular, we want to visit each of the classes defined in the module and explain their main purposes. We suggest this notebook to be used in Binder:
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/MarcelBalsiger/ngl_resum/master?filepath=%2Fdocs%2Fnglresum.ipynb) 

To have this example working as a jupyter notebook, one needs to have the packages numpy, physt and - obviously - ngl\_resum installed. The easiest way to do this is to use <code>pip install ngl_resum</code>. Details may be found here: [https://packaging.python.org/tutorials/installing-packages/#use-pip-for-installing](https://packaging.python.org/tutorials/installing-packages/#use-pip-for-installing)

## Imports

We start by importing the package ngl\_resum and numpy:

In [1]:
import ngl_resum as ngl
import numpy as np

## FourVector

We start with the <code>FourVector</code> class. As its name suggests, this class is used to describe fourvectors and contains some information specifically used in collider physics. To instantiate a <code>FourVector</code>, we have to feed all four components of it. Let us define <code>fvA</code> with energy $e$ <code>energyFvA</code> and momenta $p_i$ <code>iMomFvA</code>:

In [2]:
energyFvA=6.9
xMomFvA=4.2
yMomFvA=3.5
zMomFvA=1.2
fvA=ngl.FourVector(energyFvA,xMomFvA,yMomFvA,zMomFvA)
print(fvA)

[6.9,4.2,3.5,1.2]


### Attributes

Of course, we can access the four individual coordinates:

In [3]:
print("energy: ",fvA.e,"\nx-mom.: ",fvA.px,\
              "\ny-mom.: ",fvA.py,"\nz-mom.: ",fvA.pz)

energy:  6.9 
x-mom.:  4.2 
y-mom.:  3.5 
z-mom.:  1.2


In some cases, it may become useful to have the momentum vector displayed as a numpy-array:

In [4]:
print("numpy-array: ",fvA.vec)

numpy-array:  [6.9 4.2 3.5 1.2]


The two angles $\theta$ (angle between the z-axis or beam-axis)and $\phi$ (angle in the x-y-plane) of the three-vector are attributes: 

In [5]:
print("theta: ",fvA.theta,"\nphi: ",fvA.phi)

theta:  1.3547308176908472 
phi:  0.6947382761967031


We can also access the mass and the velocity of the particle:

In [6]:
print("mass: ",fvA.m,"\nvelocity: ",fvA.beta)

mass:  4.034848200366403 
velocity:  0.811205911255451


The length of the spatial vector $\sqrt{p_x^2+p_y^2+p_z^2}$ can also be accessed:

In [7]:
print("np.sqrt(px*px+py*py+pz*pz): ",fvA.absSpace)

np.sqrt(px*px+py*py+pz*pz):  5.597320787662612


Collider-physics specific attributes are the transverse energy $E_T$, the transverse momentum $p_T$, the rapidity $y=\frac{1}{2}\ln\frac{e+p_z}{e-p_z}$ and the pseudorapidity $\eta=-\ln\left(\tan\frac{\theta}{2}\right)$:

In [8]:
print("transverse energy: ",fvA.eT,"\ntransverse momentum: ",fvA.pT,\
              "\nrapidity: ",fvA.rap,"\npseudorapidity: ",fvA.pseudorap)

transverse energy:  6.7395647606579505 
transverse momentum:  5.4671747731346585 
rapidity:  0.1756989434189443 
pseudorapidity:  0.2177665445807071


### Operations

Let us instantiate another <code>FourVector</code>:

In [9]:
fvB=ngl.FourVector(5,4,3,0)

We can now add and subtract the fourvectors with the usual operators:

In [10]:
print("fvA+fvB:",fvA+fvB,"\nfvA-fvB: ",fvA-fvB)

fvA+fvB: [11.9,8.2,6.5,1.2] 
fvA-fvB:  [1.9000000000000004,0.20000000000000018,0.5,1.2]


The multiplication operator $*$ can be used to give a scalar product of two fourvectors or as the multiplication of a scalar. Note that we use te mostly-minus metric (+ - - -):

In [11]:
print("fvA*fvB:",fvA*fvB,"\n10*fvA: ",10*fvA)

fvA*fvB: 7.199999999999999 
10*fvA:  [69.0,42.0,35.0,12.0]


The division by a scalar does work, too:

In [12]:
print("fvA/10:",fvA/10)

fvA/10: [0.6900000000000001,0.42000000000000004,0.35,0.12]


### Methods

To measure the squared angular distance $\Delta R^2=\Delta\phi^2+\Delta\eta^2=|\phi_A-\phi_B|^2+|\eta_A-\eta_B|^2$ between two fourvectors, we can use 

In [13]:
print("deltaR^2:",fvA.R2(fvB)," or ",fvB.R2(fvA))

deltaR^2: 0.050047515262147006  or  0.050047515262147006


while the cosine of the spatial angle between two fourvectors can be accessed by

In [14]:
print("cosTheta:",fvA.costheta(fvB)," or ",fvB.costheta(fvA))

cosTheta: 0.9754666932856004  or  0.9754666932856004


We can check, whether the <code>FourVector</code> is massive or massless. A <code>FourVector</code> <code>a</code> is treated as massive (or time-like), if <code>a*a</code> is larger than $10^{-7}$, otherwise it is treated as massless (or light-like):

In [15]:
fvA.isMassive()

True

In [16]:
fvA.isMassless()

False

In [17]:
fvB.isMassive()

False

In [18]:
fvB.isMassless()

True

We can check whether two FourVectors are the same. We consider two FourVectors <code>a</code> and <code>b</code> to be the same, if <code>(a-b).e^2+(a-b).px^2+(a-b).py^2+(a-b).pz^2</code> is smaller than $10^{-10}$ to account for rounding errors. To apply this check, we can use

In [19]:
fvA.isSame(fvB)

False

In [20]:
fvA.isSame(fvA+ngl.FourVector(0.000000001,0.000000001,0.000000001,0))

True

One last method of the  <code>FourVector</code> class is going to be the tensor product fvA$_\mu$fvB$_\nu$ (which is probably not going to be used that often), given by 

In [21]:
print("fvA.metric.fvB:\n",fvA.tensorProd(fvB))

fvA.metric.fvB:
 [[ 34.5 -27.6 -20.7  -0. ]
 [ 21.  -16.8 -12.6  -0. ]
 [ 17.5 -14.  -10.5  -0. ]
 [  6.   -4.8  -3.6  -0. ]]


## Boost

The <code>Boost</code> class takes care of the boosting procedure as described in Section 3.1 [doi:10.1007/JHEP09(2020)029](https://inspirehep.net/literature/1798660). It takes two arbitrary momentum vectors from the lab frame and creates the boost from lab frame to the frame where these two fourvectors are back-to-back alongside the z-axis. For transparency we take the first two vectors of the event from Appendix A of above article, as given in (A.3):

In [22]:
p1=ngl.FourVector(504.7,125.6,82.44,-450.4)
u1=p1/p1.e
u2=ngl.FourVector(1,0,0,-1)

Now to get the boost accounting for the boost from the lab frame to the frame where <code>u1</code> is alongside the positive z-axis and <code>u2</code> alongside the negative z-axis, we just have to instantiate a <code>Boost</code> with the two fourvectors as arguments:

In [23]:
bst=ngl.Boost(u1,u2)

### Attributes

We have access to each single transformation $X$, $B$ and $Z$ as defined in Section 3.1 and thoroughly explained with an example in the pages after (A.3) of [doi:10.1007/JHEP09(2020)029](https://inspirehep.net/literature/1798660). Note, that each of these matrices are 4x4 numpy arrays.

We start out with the boost $X$, which is a rotation that puts the added two initial fourvectors along the x-axis:

In [24]:
np.dot(bst.X,(u1+u2).vec)

array([2.00000000e+00, 1.91568102e+00, 0.00000000e+00, 2.18575158e-16])

Now we apply the boost $B$, which removes the spatial component of above fourvector:

In [25]:
np.dot(bst.B,np.dot(bst.X,(u1+u2).vec))

array([ 5.74600946e-01, -8.88178420e-16,  0.00000000e+00,  2.18575158e-16])

Finally, we apply a second rotation $Z$ that puts the two initial vectors alongside the z-axis, with <code>u1</code> in the positive direction:

In [26]:
np.dot(bst.Z,np.dot(bst.B,np.dot(bst.X,u1.vec)))

array([ 3.87360275e-01, -3.53883589e-16, -8.32667268e-17,  1.87240671e-01])

In [27]:
np.dot(bst.Z,np.dot(bst.B,np.dot(bst.X,u2.vec)))

array([ 1.87240671e-01, -4.68375339e-16,  0.00000000e+00, -1.87240671e-01])

As we can see, the two fourvectors are now nicely aligned back-to-back. The full boost is also stored in an attribute:

In [28]:
u1prime=np.dot(bst.LABtoCMS,u1.vec)
u1prime

array([3.87360275e-01, 0.00000000e+00, 1.11022302e-16, 1.87240671e-01])

The same goes for the inverse boost:

In [29]:
u1BoostedBack=np.dot(bst.CMStoLAB,u1prime)
u1BoostedBack

array([ 1.        ,  0.24886071,  0.16334456, -0.89241133])

In [30]:
u1BoostedBack-u1.vec

array([ 4.44089210e-16, -1.11022302e-16,  2.77555756e-17, -2.22044605e-16])

### Methods

Of course, the numpy arrays are not easy to handle as we have to keep in mind which variable is a <code>FourVector</code> and which one a numpy array. We have a shortcut to erase this problem. We can take the boost and apply it on any <code>FourVector</code> and get back the <code>FourVector</code> in the new frame as follows:

In [31]:
fvu1prime=bst.boostLABtoCMS(u1)
fvu1prime

[0.38736027472048606,0.0,1.1102230246251565e-16,0.18724067086957508]

In [32]:
fvu1BoostedBack=bst.boostCMStoLAB(fvu1prime)
fvu1BoostedBack

[1.0000000000000004,0.24886070933227647,0.16334456112542106,-0.8924113334654252]

In [33]:
fvu1BoostedBack.isSame(u1)

True

## Hist

The <code>Hist</code> class acts as an adapter to the physt package and is immensly based on it. It accounts for the histograms $R(t)$ that is the result of the resummation (see (4.3) of [doi:10.1007/JHEP09(2020)029](https://inspirehep.net/literature/1798660)).

When initializing a <code>Hist</code>, we at least need to provide a number of bins <code>nbins</code> and a maximal value for $t$, <code>tmax</code>:

In [34]:
nbins=10
tmax=0.1
hst=ngl.Hist(nbins, tmax)

In [35]:
hst

    t   | entries  
--------|----------
 0.0050 | 0.000000
 0.0150 | 0.000000
 0.0250 | 0.000000
 0.0350 | 0.000000
 0.0450 | 0.000000
 0.0550 | 0.000000
 0.0650 | 0.000000
 0.0750 | 0.000000
 0.0850 | 0.000000
 0.0950 | 0.000000

Another possibility is to also calculate an error estimate of each bin:

In [36]:
hstErr=ngl.Hist(nbins,tmax,errorHistCalc=True)

In [37]:
hstErr

    t   | entries  |  error  
--------|----------|---------
 0.0050 | 0.000000 | 0.000000
 0.0150 | 0.000000 | 0.000000
 0.0250 | 0.000000 | 0.000000
 0.0350 | 0.000000 | 0.000000
 0.0450 | 0.000000 | 0.000000
 0.0550 | 0.000000 | 0.000000
 0.0650 | 0.000000 | 0.000000
 0.0750 | 0.000000 | 0.000000
 0.0850 | 0.000000 | 0.000000
 0.0950 | 0.000000 | 0.000000

Compared to the rest of the classes we switch the order and postpone the discussion of the attributes to after the methods and operations. This is due to the fact that the methods are mainly used to populate the histograms to avoid looking at a wall of zeroes in the discussion of the attributes.

For the sake of streamlinedness, we will stop discussing the more involved case of the error estimation at this point. The discussion thereof is quite involved and provides little insight. We will look at the extraction of the error from the histogram later.

### Methods

We have two functions that can be used to set a whole histogram to zero or to one:

In [38]:
hst.setOne()
hst

    t   | entries  
--------|----------
 0.0050 | 1.000000
 0.0150 | 1.000000
 0.0250 | 1.000000
 0.0350 | 1.000000
 0.0450 | 1.000000
 0.0550 | 1.000000
 0.0650 | 1.000000
 0.0750 | 1.000000
 0.0850 | 1.000000
 0.0950 | 1.000000

In [39]:
hst.setZero()
hst

    t   | entries  
--------|----------
 0.0050 | 0.000000
 0.0150 | 0.000000
 0.0250 | 0.000000
 0.0350 | 0.000000
 0.0450 | 0.000000
 0.0550 | 0.000000
 0.0650 | 0.000000
 0.0750 | 0.000000
 0.0850 | 0.000000
 0.0950 | 0.000000

To populate the histogram, we can use <code>addToBin</code> by specifying the value of <code>t</code> at which we add a weight <code>w</code>:

In [40]:
tVal=0.053
w=0.696969
hst.addToBin(tVal,w)
hst

    t   | entries  
--------|----------
 0.0050 | 0.000000
 0.0150 | 0.000000
 0.0250 | 0.000000
 0.0350 | 0.000000
 0.0450 | 0.000000
 0.0550 | 0.696969
 0.0650 | 0.000000
 0.0750 | 0.000000
 0.0850 | 0.000000
 0.0950 | 0.000000

### Operators

Let us start with a disclaimer - we assume the two histograms to be initialized with the same number of bin <code>nbins</code> and the same maximal $t$ value <code>tmax</code>. If this is not the case, anything might happen.

To show the use of some operators, we will populate two histograms with some random numbers:

In [41]:
hst1=ngl.Hist(nbins, tmax)
hst2=ngl.Hist(nbins, tmax)
for i in range(0,50):
    hst1.addToBin(tmax*np.random.random_sample(),np.random.random_sample())
    hst2.addToBin(tmax*np.random.random_sample(),np.random.random_sample())

Let us have a look at how these historgams are populated:

In [42]:
hst1

    t   | entries  
--------|----------
 0.0050 | 2.102598
 0.0150 | 5.474357
 0.0250 | 3.765161
 0.0350 | 1.790246
 0.0450 | 0.792018
 0.0550 | 2.373341
 0.0650 | 1.990888
 0.0750 | 1.367947
 0.0850 | 4.934581
 0.0950 | 1.853173

In [43]:
hst2

    t   | entries  
--------|----------
 0.0050 | 2.918347
 0.0150 | 3.740859
 0.0250 | 3.559869
 0.0350 | 1.760655
 0.0450 | 2.113326
 0.0550 | 4.627729
 0.0650 | 2.237888
 0.0750 | 0.591951
 0.0850 | 4.630542
 0.0950 | 1.203527

We can add and subtract the histograms. This sums (or subtracts) the entry of each bin:

In [44]:
hst1+hst2

    t   | entries  
--------|----------
 0.0050 | 5.020945
 0.0150 | 9.215216
 0.0250 | 7.325029
 0.0350 | 3.550901
 0.0450 | 2.905344
 0.0550 | 7.001070
 0.0650 | 4.228776
 0.0750 | 1.959898
 0.0850 | 9.565123
 0.0950 | 3.056700

In [45]:
hst1-hst2

    t   | entries  
--------|----------
 0.0050 | -0.815749
 0.0150 | 1.733499
 0.0250 | 0.205292
 0.0350 | 0.029590
 0.0450 | -1.321308
 0.0550 | -2.254388
 0.0650 | -0.247000
 0.0750 | 0.775997
 0.0850 | 0.304039
 0.0950 | 0.649647

The multiplication of two Hists multiplies the entry of each bin, and we can also multiply with a scalar (which multiplicates each entry by the scalar):

In [46]:
hst1*hst2

    t   | entries  
--------|----------
 0.0050 | 6.136110
 0.0150 | 20.478796
 0.0250 | 13.403477
 0.0350 | 3.152005
 0.0450 | 1.673791
 0.0550 | 10.983180
 0.0650 | 4.455385
 0.0750 | 0.809758
 0.0850 | 22.849784
 0.0950 | 2.230344

In [47]:
10*hst1

    t   | entries  
--------|----------
 0.0050 | 21.025980
 0.0150 | 54.743571
 0.0250 | 37.651608
 0.0350 | 17.902456
 0.0450 | 7.920177
 0.0550 | 23.733412
 0.0650 | 19.908881
 0.0750 | 13.679475
 0.0850 | 49.345810
 0.0950 | 18.531734

Division by a scalar is possible as well:

In [48]:
hst1/10

    t   | entries  
--------|----------
 0.0050 | 0.210260
 0.0150 | 0.547436
 0.0250 | 0.376516
 0.0350 | 0.179025
 0.0450 | 0.079202
 0.0550 | 0.237334
 0.0650 | 0.199089
 0.0750 | 0.136795
 0.0850 | 0.493458
 0.0950 | 0.185317

### Attributes

Let us finally look at how to access the data in <code>Hist</code>. The Histograms certainly knows about the number of bins and maximal $t$:

In [49]:
print("nbins: ",hst1.nbins,"\ntmax: ",hst1.tmax)

nbins:  10 
tmax:  0.1


To access the entries of the histogram, we can do so:

In [50]:
hst1.entries

array([2.10259796, 5.47435712, 3.76516075, 1.79024562, 0.7920177 ,
       2.37334117, 1.99088811, 1.36794745, 4.93458098, 1.85317337])

The bin values can be read out as well. As it is sometimes useful to have the lower or upper bin boundary or the central value, we have created access to all of them:

In [51]:
print("central bin values: ",hst1.centerBinValue)
print("lower bin boundary: ",hst1.lowerBinBoundary)
print("upper bin boundary: ",hst1.upperBinBoundary)

central bin values:  [0.005, 0.015, 0.025, 0.035, 0.045, 0.055, 0.065, 0.07500000000000001, 0.08499999999999999, 0.095]
lower bin boundary:  [0.0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09]
upper bin boundary:  [0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1]


Now let us have a quick glance at the error estimations of the bins. Note, that while the representation of the histogram comes with the error itself, due to intricacies of the error computation when multiplying histograms (which is used in the showering procedure), we are only able to access the squared of the error estimate. To illustrate this, let us first populize the <code>hstErr</code> from above and show its representation:

In [52]:
for i in range(0,50):
    hstErr.addToBin(tmax*np.random.random_sample(),np.random.random_sample())
hstErr

    t   | entries  |  error  
--------|----------|---------
 0.0050 | 1.295799 | 0.997647
 0.0150 | 0.542311 | 0.527699
 0.0250 | 1.156891 | 0.837240
 0.0350 | 3.134448 | 1.461181
 0.0450 | 1.987160 | 1.212088
 0.0550 | 1.799335 | 1.103540
 0.0650 | 3.308246 | 1.490670
 0.0750 | 4.888158 | 1.768580
 0.0850 | 5.766296 | 2.122759
 0.0950 | 0.334684 | 0.296820

Now we will access the squared error of the bins:

In [53]:
hstErr.squaredError

array([0.99530047, 0.27846598, 0.70097064, 2.1350506 , 1.46915656,
       1.21780011, 2.2220969 , 3.127874  , 4.50610368, 0.08810237])

This might seem a little bit odd. For more insight into the error handling we refer to the documentation of the example codes. 

## Event

Now we get to the core of the package. An instance of <code>Event</code> contains all the reevant information to start one showering. We will not go too deep into details here, but mainly refer to the two example codes. To instantiate an <code>Event</code>, one can either feed it 
* a dipole (using the <code>feedDipole</code> parameter), or
* an <code>pylhe.LHEEvent</code> read-in via <code>pylhe.readLHE</code> (using the <code>eventFromFile</code> parameter)

To each of those we have an example code.While we will not explain every attribute and method of this class in detail, we still want to give an overview of some intricacies. 

First of all we want to discuss the feedDipole feature. Via <code>Event(feedDipole=dipole)</code> we can set up the showering of one single dipole, consisting of two fourVectors in an array: 

In [54]:
leg1=ngl.FourVector(1,0,0,0.5)
leg2=ngl.FourVector(1,0,0,-0.5)
dipole=[leg1,leg2]
evDip=ngl.Event(feedDipole=dipole)

This feature is straightforward enough. We have set up this dipole for showering.

The other feature of <code>Event</code> is the more intricate showering of an event read in from a .lhe-file. After feeding the <code>pylhe.LHEEvent</code> into the parameter <code>eventFromFile</code> we have two additional options, namely
* whether we want to form the color-connected dipoles between the incoming and outgoing particles of the event or between the incoming and intermediate ones, and
* whether we also want to account for the decay dipoles between the intermediate and the outgoing particles.

An example where we shower both the dipoles formed by the incoming-intermediate particles and the intermediate-outgoing particles is given for example in Section 5 of [doi:10.1007/JHEP09(2020)029](https://inspirehep.net/literature/1798660) .

To keep this documentation simple, we will not actually read in a .lhe-file, and therefore can not go hands-on here. If you want to play around with this feature, we suggest you move to the example code.

To instantiate an <code>Event</code> by an <code>event=pylhe.LHEEvent</code>, we have to use <br><code>evLHE=ngl.Event(eventFromFile="pylhe.LHEEvent")</code>.<br>
It sets up the <code>Event</code> with the default case of color-sorting the incoming and outgoing particles. To set up the showering of the incoming-intermediate particle dipoles, we have to use <br><code>evLHE=ngl.Event(eventFromFile=pylhe.LHEEvent, productionDipoles='intermediate')</code>,<br>
and if we not only want to have the production dipoles showered, but also the dipoles associated to the decay, we have to use <br><code>evLHE=ngl.Event(eventFromFile=pylhe.LHEEvent,productionDipoles='intermediate',decayDipoles=True)</code>.<br> 
Note that you will probably seldom use these additional features and most oftenly only have to use <code>evLHE=ngl.Event(eventFromFile="pylhe.LHEEvent")</code>, except if you work with top quarks.

Note that if you instantiate an <code>Event</code> using a <code>pylhe.LHEEvent</code>, you have access to the weight as well as an array of the <code>FourVector</code> of each kind of particles in the form of an attribute. You can access the weight of the event via 
<code>ev=ngl.Event(eventFromFile="pylhe.LHEEvent")</code><br>
<code>ev.weight</code><br>
If you want the fourvectors of all incoming up-type quarks and antiquarks, you can access them via <br> 
<code>ev=ngl.Event(eventFromFile="pylhe.LHEEvent")</code><br>
<code>ev.incomingUp</code>.<br>
In the same way, you can access <code>ev.statusType</code>, with <code>status</code> being <code>incoming</code>,<code>intermediate</code> or <code>outgoing</code>, and <code>Type</code> being <code>Down</code>, <code>Up</code>, <code>Strange</code>, <code>Charm</code>, <code>Bottom</code>, <code>Top</code>, <code>Electron</code>, <code>ENeutrino</code>, <code>Muon</code>, <code>MNeutrino</code>, <code>Tau</code>, <code>TNeutrino</code>, <code>Gluon</code>, <code>Photon</code>, <code>ZBoson</code>, <code>WBoson</code> or <code>Higgs</code>.

## OutsideRegion

Just as the <code>Event</code> class, <code>OutsideRegion</code> is very specific to the observable you are considering. Its whole purpose is to tell the <code>Shower</code>, whether a <code>FourVector</code> is pointing into the region where it gets vetoed. The nomenclature of **outside** comes from the textbook example of the interjet energy flow, where radiation that is not inside the jets gets vetoed. 

We can initiate the <code>OutsideRegion</code> with or without an <code>Event</code>. Whether you should feed it an <code>Event</code> or not depends on whether the region where you want to  veto radiation depends on the distribution of the outgoing particles. We have one example code each for the usage with and without an <code>Event</code>.

An instance of <code>OutsideRegion</code> doesn't do anything. It containes the stub of a method <code>outside(self,v)</code> which needs to be implemented by you. To do so, you need to write a method

In [55]:
def _outside(self,v):
    #
    # Code that checks whether v is a FourVector
    # landing outside. 
    #
    retVal=True  # if v outside
    retVal=False # if v not outside
    return (retVal)

and - after creating an instance of OutsideRegion

In [56]:
outsideRegion=ngl.OutsideRegion()

exchange the stub of <code>outside(self,v)</code> of your instance <code>outsideRegion</code> to your method by invoking

In [57]:
outsideRegion.outside = _outside.__get__(outsideRegion,ngl.OutsideRegion)

For more details we refer to the two example codes which show the handling of the <code>OutsideRegion</code> class.

## Shower

Let us now get to the core of our resummation precedure, the showering of an <code>Event</code>. To instantiate a <code>Shower</code>, we feed it the following parameters (most of which come with a default choice):

In [58]:
# event: Event,
# outsideRegion: OutsideRegion,
# nsh: int=50, 
# nbins: int=100, 
# tmax: float=0.1, 
# cut: float=5.0, 
# fixedOrderExpansion: bool=True,
# virtualSubtracted: bool=False

Of these parameters, <code>event</code> and <code>outsideRegion</code> unsurprisingly contain the <code>Event</code> to shower with the respective <code>OutsideRegion</code> under consideration. The number of showerings you want to apply on the <code>event</code>  is fed in via <code>nsh</code> (<code>50</code> by default). To create the <code>Hist</code> which will eventually be the result of the resummation, we can change the <code>nbins</code> (<code>100</code> by default) and <code>tmax</code> (<code>0.1</code> by default). We can also change the collinear cutoff <code>cut</code> (<code>5.0</code> by default), which corresponds to $\eta_{max}$ as discussed in (A.14) of [doi:10.1007/JHEP09(2020)029](https://inspirehep.net/literature/1798660). Finally, we can decide whether or not we want to calculate the first two expansion parameters of the resummation as given in (4.3) of [doi:10.1007/JHEP09(2020)029](https://inspirehep.net/literature/1798660) in <code>fixedOrderExpansion</code> (<code>True</code> by default). The last option is <code>virtualSubtracted</code> will most likely have to be turned off (as is the default), it is used to subtract the  global  one-loop  part  from  the  soft  anomalous dimension as discussed in (3.5) of [doi:10.1007/JHEP04(2019)020](https://inspirehep.net/literature/1717208).

Instead of going through the details of the showering precedure we refer to Appendix A of [doi:10.1007/JHEP09(2020)029](https://inspirehep.net/literature/1798660), where this is explained in a very detailed fashion.